version: "3.9"
services: 
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports: 
      - 3000:80
    networks:
      - a105
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    container_name: backend
    build: 
      context: ./backend/a105
    ports: 
      - 8080:8080
    networks:
      - a105
    restart: unless-stopped
networks: 
  a105:
